cv/urls.py
from django import urls
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('',include('index.urls', namespace='index')),
    path("reco/", include('recommendation.urls', namespace='reco')),
    path('admin/', admin.site.urls),
    path("login/", include('account.urls', namespace='account')),
    path("logout/", auth_views.LogoutView.as_view(), name = "logout", kwargs={'next_page': '/'}),
]

index/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('work/', views.WorkView.as_view(), name='work'),
    path('education/', views.EducationView.as_view(), name='education'),
    path('portfolio/', views.ProtfolioView.as_view(), name='portfolio'),
    path('ortho/', views.OrthoView.as_view(), name='ortho'),
    path('weather/', views.WeatherView.as_view(), name='weather'),
    path('todo/', views.TodoView.as_view(), name='todo'),
    path('sudoku/', views.SudokuView.as_view(), name='sudoku'),
    path('contact/', views.MessageCreateView.as_view(), name='contact'),
    path('thanks/', views.ThanksMessageView.as_view(), name='thanks_message'),
    path('dl/<str:filepath>/', views.download_cv),
    path('my_messages',views.MessagesListView.as_view(),name="my_messages"),
    path('my_messages/<pk>/read',views.message_read,name="message_read"),
    path('my_messages/<pk>/delete',views.MessageDelete.as_view(),name="message_delete"),

]

recommendation/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "reco"

urlpatterns = [
    path("", views.ValidRecoListView.as_view(), name = "validreco_list"),
    path("list", views.RecoListView.as_view(), name = "reco_list"),
    path("new", views.RecoCreateView.as_view(), name = "reco_create"),
    path("thanks", views.ThanksTemplateView.as_view(), name = "thanks"),
    path("<pk>", views.RecoDetailView.as_view(), name = "reco_detail"),
    path("<pk>/update", views.RecoUpdateView.as_view(), name = "reco_update"),
    path("<pk>/delete", views.RecoDeleteView.as_view(), name = "reco_delete"),
    path("<pk>/publish", views.reco_publish, name = "reco_publish"),

]

recommendation/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
# Create your models here.


class Recommendation(models.Model):
    CHOICES = [
        ('We work together in the same team or on the same project',
        'We work together in the same team or on the same project'), 
        ('Blaise was under my responsability','Blaise was under my responsability'),
        ('We work together inderectly','We work together inderectly'),
        ("I was his customer","I was his customer"),
        ("I heard about his skills","I heard about his skills"),
    ]
    
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    job = models.CharField(max_length = 50)
    relationship = models.CharField(max_length = 200, choices = CHOICES)
    comment = models.TextField(max_length = 1000, blank = True,
                               null = True, default = None)
    create_date = models.DateTimeField(default = timezone.now)
    publish_date = models.DateTimeField(blank = True, null = True)


    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse("reco:reco_detail", kwargs={"pk": self.pk})

    def publish(self):
        self.publish_date = timezone.now()
        self.save()    
        
    

recommendation/forms.py
from django import forms
from .models import Recommendation


class RecommendationForm(forms.ModelForm):
    
    class Meta:
        model = Recommendation
        fields = ("first_name","last_name",
                  "job","relationship","comment")

  

recommendation/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls.base import reverse_lazy
from django.utils import timezone
from .models import Recommendation
from .forms import RecommendationForm
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView,ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Template views: 

class ThanksTemplateView(TemplateView):
    template_name = "thanks.html"


# List views:

class ValidRecoListView(ListView):
    model = Recommendation
    template_name = "validreco_list.html"

    def get_queryset(self):
        return super().get_queryset().filter(
            publish_date__lte=timezone.now()).order_by("-publish_date")


class RecoListView(LoginRequiredMixin,ListView):
    model = Recommendation
    template_name = "reco_list.html"
    login_url = '/login/'

    def get_queryset(self):
        return super().get_queryset().filter(
            publish_date__isnull=True).order_by('-create_date')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)  
        # Add in the counts of read messages
        context['unpublished_reco'] = Recommendation.objects.filter(publish_date__isnull = True).count()
        return context 

# CRUD views : 

class RecoCreateView(CreateView):
    model = Recommendation
    form_class = RecommendationForm
    template_name = "reco_create.html"
    success_url = reverse_lazy('reco:thanks')
    

class RecoDetailView(LoginRequiredMixin,DetailView):
    model = Recommendation
    template_name = "reco_detail.html"
    login_url = '/login/'


class RecoUpdateView(LoginRequiredMixin,UpdateView):
    model = Recommendation
    form_class = RecommendationForm
    template_name = "reco_update.html"
    redirect_field_name = "reco/reco_detail.html"
    login_url = '/login/'


class RecoDeleteView(LoginRequiredMixin,DeleteView):
    model = Recommendation
    success_url = reverse_lazy('reco:reco_list')
    login_url = '/login/'


# Function based views :

@login_required
def reco_publish(request,pk):
    reco = get_object_or_404(Recommendation,pk=pk)
    reco.publish()
    return redirect('reco:reco_list')

recommendation/templates/recommendation/reco_create.html
{% extends 'base.html' %}
{% load bulma_tags %}
{% block body_block %}

<section class="hero is-small is-info " id="main-hero">
    <div class="hero-body">
        <div id="hero-elt">
            <h1 class="title is-3" style="font-weight: 300;">
                Let the people know how nice I am
            </h1>
        </div>
    </div>
</section>
<section class="form">
<div class='container is-fluid'>
    <div class="columns is-mobile is-centered py-5">
        <div class="column is-full-mobile is-two-thirds-tablet is-half-desktop">
            <form class="form" action="" method="POST">
                {% csrf_token %}
                {{form|bulma}}
                <div class="field has-text-centered">
                    <input type="submit" class="button has-text-white-bis" value="Submit" style="background-color: #0077b6"></input>
                </div>
                <input type="hidden" name="next" value="{{ next }}"/>
            </form>
        </div>
    </div>    
</div>
</section>

{% endblock body_block%}

recommendation/templates/recommendation/reco_detail.html
{% extends 'base.html' %}
{% block body_block %}
<section class="hero is-small is-info " id="main-hero">
    <div class="hero-body">
        <div id="hero-elt">
            <h1 class="title is-3" style="font-weight: 300;">
                Details
            </h1>
        </div>
    </div>
</section>
<section>
<div class='container is-fluid'>
    <div class="columns is-mobile is-centered py-5">
        <div class="column is-full-mobile is-two-thirds-tablet is-half-desktop">
            <div class="content">
                <p class="title is-5">{{recommendation.first_name}} {{recommendation.last_name}}</p>
                <p class="title is-5">{{recommendation.job}}</p>
                <p class="subtitle is-5">{{recommendation.relationship}}</p>
                <p class="subtitle is-6">Recommendation created on {{recommendation.create_date}}</p>
                <p>{{recommendation.comment}}</p>
            </div>
            <div class = "buttons">
                <a class="button is-primary" href = "{% url 'reco:reco_publish' pk=recommendation.pk %}">Approve</a>
                <a class= "button is-info" href="{% url 'reco:reco_update' pk=recommendation.pk %}">Update</a>
                <a class="button is-danger" href = "{% url 'reco:reco_delete' pk=recommendation.pk %}">Delete</a>
            </div>    
        </div>
    </div>
</div>
</section>

{% endblock %}

recommendation/templates/recommendation/reco_list.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}

<section class="hero is-small is-info " id="main-hero">
    <div class="hero-body">
        <div id="hero-elt">
            {% if unpublished_reco > 0 %}
            <h1 class="title is-3" style="font-weight: 300;">
                Recommendation(s) to be approved
            </h1>
            {% else %}
            <h1 class="title is-3" style="font-weight: 300;">
                You have no recommendation to be approved
            </h1>
            {% endif %}
        </div>
    </div>
</section>

<section>
{% for reco in recommendation_list %} 
    <div class="columns is-desktop" style="margin:20px">
        <div class="column">
            <div class="box" style="padding-bottom:48px">
                <div class ="content">
                    <a class="subtitle is-5" href="{% url 'reco:reco_detail' pk=reco.pk %}">From {{reco.first_name}} {{reco.last_name}}</a>
                    <h3 class="subtitle is-5">{{reco.job}}</h3>
                    <p>{{reco.relationship}}<br>{{reco.create_date|date:"D M Y"}}</p>
                    <a class="button is-primary" href = "{% url 'reco:reco_publish' pk=reco.pk %}">Approve</a>
                    <a class="button is-danger" href = "{% url 'reco:reco_delete' pk=reco.pk %}">Delete</a>
                </div>
            </div>  
        </div>
    </div>  
{% endfor %}         
</section>
{% endblock body_block %} 

recommendation/templates/recommendation/reco_update.html
{% extends 'base.html' %}
{% load bulma_tags %}
{% block body_block %}
<section class="hero is-small is-info " id="main-hero">
    <div class="hero-body">
        <div id="hero-elt">
            <h1 class="title is-3" style="font-weight: 300;">
                Modify a recommendation
            </h1>
        </div>
    </div>
</section>

<div class='container is-fluid'>
    <div class="columns is-mobile is-centered py-5">
        <div class="column is-full-mobile is-two-thirds-tablet is-half-desktop">
            <form class="form" action="" method="POST">
                {% csrf_token %}
                {{form|bulma}}
                <div class="field has-text-centered">
                    <input type="submit" class="button has-text-white-bis" value="Submit" style="background-color: #0077b6"></input>
                </div>
                <input type="hidden" name="next" value="{{ next }}"/>
            </form>
        </div>
    </div>    
</div>





{% endblock body_block %}

recommendation/templates/recommendation/recommendation_confirm_delete.html
{% extends 'base.html' %}
{% block body_block %}
<section class="hero is-medium is-info " id="main-hero">
    <div class="hero-body">
        <div id="hero-elt">
            <form method="POST">
            {% csrf_token %}
            <h1 class = "title is-6" style:'font-weight: 100;'>Are you sure you want to delete this recommendation ?</h1>
            <input type="submit" class="button is-primary" value="Yes">
            <a class="button is-danger" href= {% url 'index:my_messages' %}>No, wait...</a>

</form>
        </div>               
    </div>
</section>
{% endblock body_block %}

recommendation/templates/recommendation/thanks.html
{% extends 'base.html' %}
{% block body_block %}

<section class="hero is-medium is-info " id="main-hero">
    <div class="hero-body">
        <div id="hero-elt">
            <h1 class="title is-1" style="font-weight: 300;">
                Copy that ! 
            </h1>
            <h2 class="subtitle is-3" style="font-weight: 300;">
                I will review your recommendation and eventually publish it on this website. 
            </h2>
        </div>               
    </div>
</section>

{% endblock body_block %}

recommendation/templates/recommendation/validreco_list.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}

<section class="section" style="background-color:#0096c7;">
    <div class="container" >
        <!-- Start Carousel -->
        <div id="carousel-demo" class="carousel">
            {% for reco in recommendation_list  %}
                <div class="item" style = "padding: 30px; color:white; padding-left:60px;padding-right:60px">
                    <p class ="has-text-centered" style="padding-bottom:10px; font-style:italic;">{{reco.comment}}</p>
                    <p class ="has-text-centered">{{reco}}</p>
                    <p class ="has-text-centered">{{reco.job}}</p>
                    <p class ="has-text-centered">{{reco.relationship}}</p>
                </div>
            {% endfor %}
        <!-- End Carousel -->
    </div>
</section>

<section class="section has-text-centered">
    <span id="button">
        <a href = "{% url 'reco:reco_create' %}" class="button has-text-white-bis" style="background-color: #0077b6">
            Leave a recommendation ! 
        </a>
    </span>
</section>    


<script>
    bulmaCarousel.attach('#carousel-demo', {
        slidesToScroll: 1,
        slidesToShow: 1
    });
</script>        
{% endblock body_block %} 