cv/urls.py
from django import urls
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('',include('index.urls', namespace='index')),
    path("reco/", include('recommendation.urls', namespace='reco')),
    path('admin/', admin.site.urls),
    path("login/", include('account.urls', namespace='account')),
    path("logout/", auth_views.LogoutView.as_view(), name = "logout", kwargs={'next_page': '/'}),
]

index/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('work/', views.WorkView.as_view(), name='work'),
    path('education/', views.EducationView.as_view(), name='education'),
    path('portfolio/', views.ProtfolioView.as_view(), name='portfolio'),
    path('ortho/', views.OrthoView.as_view(), name='ortho'),
    path('weather/', views.WeatherView.as_view(), name='weather'),
    path('todo/', views.TodoView.as_view(), name='todo'),
    path('sudoku/', views.SudokuView.as_view(), name='sudoku'),
    path('contact/', views.MessageCreateView.as_view(), name='contact'),
    path('thanks/', views.ThanksMessageView.as_view(), name='thanks_message'),
    path('dl/<str:filepath>/', views.download_cv),
    path('my_messages',views.MessagesListView.as_view(),name="my_messages"),
    path('my_messages/<pk>/read',views.message_read,name="message_read"),
    path('my_messages/<pk>/delete',views.MessageDelete.as_view(),name="message_delete"),

]

index/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Message(models.Model):
    id = models.AutoField(primary_key=True)
    mail = models.EmailField(max_length = 254)
    text = models.TextField()
    read = models.BooleanField(default = False)
    date = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return self.mail

    def is_read(self):
        self.read = True
        self.save()

index/templates/index/contact.html
{% extends 'base.html' %}
{% load bulma_tags %}
{% block body_block %}

<section class="hero is-small is-info " id="main-hero">
    <div class="hero-body">
        <div id="hero-elt">
            <h1 class="title is-3" style="font-weight: 300;">
                Contact
            </h1>
            <h2 class="subtile is-3" style="font-weight: 300;">
                Send me a message
            </h2>
        </div>
    </div>
</section>
<section class="form">
<div class='container is-fluid'>
    <div class="container is-fluid columns is-mobile is-centered py-5">
        <div class="column is-full-mobile is-two-thirds-tablet is-half-desktop">
            <form class="form" action="" method="POST">
                {% csrf_token %}
                {{form|bulma}}
                <div class="field has-text-centered">
                    <input type="submit" class="button has-text-white-bis" value="Send" style="background-color: #0077b6"></input>
                </div>
                <input type="hidden" name="next" value="{{ next }}"/>
            </form>
        </div>
    </div>    
</div>
</section>

{% endblock body_block%}

index/templates/index/education.html
{% extends 'base.html' %}
{% block body_block %}

<section class="hero is-small is-info " id="main-hero">
    <div class="hero-body">
        <div id="hero-elt">
            <h1 class="title is-3" style="font-weight: 300;">
                Education
            </h1>
        </div>
    </div>
</section>

<section>
    <div class="columns is-desktop" style="margin:20px">
        <div class="column">
            <div class="box" style="padding-bottom:48px">
                <div class ="content">
                    <h2 class="title is-5">University</h2>
                    <h3 class="title is-6">Universidade de Lisboa – ESHTE</h3>
                    <p>Master’s degree in Tourism and communication</br>2012-2014</p>
                    <h3 class="title is-6">Université Paris X Nanterre</h3>
                    <p>Bachelor’s degree in Geography and spatial planning</br>
                    Erasmus – Instituto de Geografia e Ordenamento do Territorio - Lisboa</br>
                    2009-2012</p>
                </div>        
            </div>
        </div>
        <div class="column">
            <div class="box" style="padding-bottom:36px;">
                <div class ="content">
                    <h2 class="title is-5">Certifications</h2>
                    <h3 class="title is-6">OpenClassrooms</h3>
                    <ul>
                        <li><a href="https://openclassrooms.com/fr/courses/1946386-comprendre-le-web">
                        Comprendre le Web</a></li>
                        <li><a href="https://openclassrooms.com/fr/courses/1603881-apprenez-a-creer-votre-site-web-avec-html5-et-css3">
                        Apprenez à créer votre site web avec HTML5 et CSS3</a></li>
                        <li><a href="https://openclassrooms.com/fr/courses/4262331-demarrez-votre-projet-avec-python">
                        Démarrez votre projet avec Python</a></li>
                        <li><a href="https://openclassrooms.com/fr/courses/235344-apprenez-a-programmer-en-python">
                        Apprenez à programmer en Python</a></li>
                    </ul> 
                    <h3 class="title is-6">Udemy</h3>
                    <ul>
                        <li><a href="https://www.udemy.com/course/python-and-django-full-stack-web-developer-bootcamp/">
                        Python and Django Full Stack Web Developer Bootcamp</a></li>    
                    </ul>
                </div>
            </div>
        </div>
    </div>      
</section>    

{% endblock body_block %} 

index/templates/index/index.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<section class="hero is-medium is-info " id="main-hero">
    <div class="hero-body">
        <div id="hero-elt">
            <h1 class="title is-1" style="font-weight: 300;">
                Blaise De Carvalho
            </h1>
            <figure class="image is-128x128" id="picture">
                <img class="is-rounded" src="{% static 'index\1534257017802.jpg' %}">
            </figure>
            <h2 class="subtitle is-3" style="font-weight: 300;">
                Junior Developer
            </h2>
            <h2 class="subtitle is-5" style="font-weight: 300;">
                Python / Django / HTML5 / CSS3 / SQL
            </h2>
            <span id="button">
                <a href = "{% static 'index\Curriculum.pdf' %}" class="button has-text-white-bis" id="bouton" style="background-color: #0077b6">
                    <i class="material-icons">
                    file_download
                    </i>
                    Download my curriculum
                </a>
            </span>
        </div>               
    </div>
</section>
<section>
    <content class="container">
        <div class="notification">
            <div class = "columns is-centered is-mobile">
                <div class = "column is-three-quarters">
                    <h1 class="title has-text-centered">About me</h1>
                    <p class="has-text-justified">After working for almost 7 years in the
                                                tourism industry, mainly in sales, I decided to
                                                start a professional retraining. For more than one year and a half, 
                                                throughout my
                                                trainings and projects, I acquired knowledge in
                                                Python3, Django, HTML5, CSS3 and some
                                                experience in relational databases (MySQL,
                                                PostgreSQL). My objective is to join a team as
                                                a Junior Web Developer where I can gain a
                                                consistent work experience and where I can
                                                use my learning ability, my adaptability and
                                                my autonomy.
                    </p>
                </div>   
            </div>
        </div>
    </content>
    <content class="container">
        <div class="notification">
            <div class = "columns is-centered">
                <div class = "column is-three-quarters">
                    <h1 class="title has-text-centered">Skills</h1>
                    <div class = "columns is-centered"> 
                        <div class = "column" style="display: flex;justify-content: center;
                        align-items: center;">
                            <figure class="image is-128x128">
                                <img src="{% static 'index\Python.png' %}">
                            </figure>
                        </div>    
                        <div class = "column" style="padding-top:60px;display: flex;justify-content: center;
                        align-items: center;">
                            <figure class="image is-128x128">
                                <img src="{% static 'index\django.png' %}">
                            </figure>
                        </div>
                        <div class = "column" style="padding-top:50px;display: flex;justify-content: center;
                        align-items: center;">
                            <figure class="image is-128x128">
                                <img src="{% static 'index\html-css.png' %}">
                            </figure>
                        </div>
                        <div class = "column" style="padding-top:70px;display: flex;justify-content: center;
                        align-items: center;">
                            <figure class="image is-128x128">
                                <img src="{% static 'index\sqlite.png' %}">
                            </figure>
                        </div>
                        <div class = "column" style="padding-top:10px;display: flex;justify-content: center;
                        align-items: center;">
                            <figure class="image is-128x128">
                                <img src="{% static 'index\postgresql.png' %}">
                            </figure>
                        </div>
                    </div>
                </div>   
            </div>
        </div>
    </content>         
</section> 
     


{% endblock body_block %}    

index/templates/index/message_confirm_delete.html
{% extends 'base.html' %}
{% block body_block %}
<section class="hero is-medium is-info " id="main-hero">
    <div class="hero-body">
        <div id="hero-elt">
            <form method="POST">
            {% csrf_token %}
            <h1 class = "title is-6" style:'font-weight: 100;'>Are you sure you want to delete this message ?</h1>
            <input type="submit" class="button is-primary" value="Yes">
            <a class="button is-danger" href= {% url 'index:my_messages' %}>No, wait...</a>

</form>
        </div>               
    </div>
</section>
{% endblock body_block %}

index/templates/index/my_messages.html
{% extends 'base.html' %}
{% block body_block %}
<section class="hero is-small is-info " id="main-hero">
    <div class="hero-body">
        <div id="hero-elt">
            <h1 class="title is-3" style="font-weight: 300;">
                {% if count_unread > 0 %}
                You have {{count_unread}} new message(s)
                {% else %}
                You have {{count_read}} message(s)
                {% endif %}
            </h1>
        </div>
    </div>
</section>

<section>
{% for message in message_list %} 
    <div class="columns is-desktop" style="margin:20px">
        <div class="column">
            {% if message.read == True %}
            <div class="box" style="padding-bottom:48px">
            {% else %}
            <div class="box" style="padding-bottom:48px;background-color:#90e0ef">
            {% endif %}
                <div class ="content">
                    <h3 class="subtitle is-5">From {{message.mail}}</h3>
                    <p>{{message.text}}</p>
                    {% if message.read == False %}
                    <a class="button is-info" href = "{% url 'index:message_read' pk=message.pk %}">Mark as read</a>
                    {% endif %}
                    <a class="button is-danger" href = "{% url 'index:message_delete' pk=message.pk %}">Delete message</a>
                </div>
            </div>  
        </div>
    </div>  
{% endfor %}         
</section>
{% endblock body_block %}

index/templates/index/ortho.html
{% extends 'base.html' %}
{% block body_block %}
<section class="hero is-small is-info " id="main-hero">
    <div class="hero-body">
        <div id="hero-elt">
            <h1 class="title is-3" style="font-weight: 300;">
                Ortholist
            </h1>
            <h2 class="subtitle is-5" style="font-weight: 300;">
                Used in this project :  Python / Django / HTML5 / CSS3 / SQL
            </h2>
            <a class="subtitle is-5" style="font-weight: 300;" href="https://github.com/Zeble1603/ortholist">
                <span class="icon">
                    <i class="fab fa-github"></i>
                </span>
                <span>Check the GitHub repository</span>
            </a>

        </div>
    </div>
</section>
<section>
    <content class="container">
        <div class="notification">
            <div class = "columns is-centered">
                <div class = "column is-three-quarters">
                    <h1 class="title has-text-centered">Why?</h1>
                    <p class="has-text-justified">My mother works as a Speech Therapist. One day, 
                    she explained to me that in France, we are sorely lacking in representatives of
                    this profession. She then showed me her waiting list : a 15cm thick file where she
                    preciously keep all the patients details she should contact if a place becomes available 
                    in her agenda. 
                    In order to make her life easier, I first advised her to use an excel file to compile 
                    all this information, but it wouldn’t solve the patient's problem : they would keep on 
                    calling to ask for appointments. 
                    That’s why I decided to create this platform. 
                    It allows the patient to raise requests for appointments and my mother to select, 
                    order and manage all the requests saved in the database.
                    </p>
                </div>   
            </div>
            <div class = "columns is-centered">
                <div class = "column is-three-quarters">
                    <h1 class="title has-text-centered">How?</h1>
                    <p class="has-text-justified">I used Django to build the backend of this website. 
                    The idea was to create two main apps inside the project : one for the patient who 
                    could create their demand, and the other for the speech therapist, who could access
                    a table of all the raised demands. It’s a basic system that uses the main functionalities 
                    of Django (Class Based views, context data, queryset…) and it was a very good exercise to 
                    put into practice what I’ve learned so far. I also learnt how to use the django-filters library 
                    to allow the Speech Therapist to sort and filter the table of data. I mainly used bulma.io as a 
                    CSS library.
                    </p>
                </div>   
            </div>
            <div class = "columns is-centered">
                <div class = "column is-three-quarters">
                    <h1 class="title has-text-centered">What could be improved ?</h1>
                    <p class="has-text-justified">
                    I am currently thinking about implementing a tool that
                    would automatically send an email to the user when they
                    raised their appointment request. 
                    </p>
                </div>   
            </div>
        </div>
    </content>
</section>
{% endblock body_block %}

index/templates/index/portfolio.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<section class="hero is-small is-info " id="main-hero">
    <div class="hero-body">
        <div id="hero-elt">
            <h1 class="title is-3" style="font-weight: 300;">
                My projects
            </h1>
        </div>
    </div>
</section>

<section class="container">
    <div class="columns" style = "margin-top:10px; margin-bottom:20px;">
        <div class="column has-text-centered is-5 is-offset-1">
            <h1 class = "subtitle is-4">
                Ortholist
            </h1>
            <p> Django / HTML5 / CSS3 / BULMA / SQL </p>
            <a class="button mt-3" href = "https://github.com/Zeble1603/ortholist">
                <span class="icon">
                    <i class="fab fa-github"></i>
                </span>
                <span>GitHub</span>
            </a>
        </div>
        <div class="column has-text-centered is-5">
            <h1 class = "subtitle is-4">
                Beautiful Weather
            </h1>
            <p>Django / HTML5 / CSS3 / BULMA / SQL </p>
            <div class = "buttons is-centered">
                <a class="button mt-3" href = "https://github.com/Zeble1603/weatherdash">
                    <span class="icon">
                        <i class="fab fa-github"></i>
                    </span>
                    <span>GitHub</span>
                </a>
                <a class="button mt-3" href = "https://beautiful-weather.herokuapp.com/">
                    Go to Website
                </a>
            </div>    
        </div>
    </div>    
    <div class="columns is-centered" style = "margin-top:10px; margin-bottom:20px;">
        <div class="column has-text-centered is-5">
            <h1 class = "subtitle is-4">
                To do List
            </h1>
            <p>Django / HTML5 / CSS3 / BULMA / SQL</p>
            <a class="button mt-3" href = "https://github.com/Zeble1603/to_doapp">
                <span class="icon">
                    <i class="fab fa-github"></i>
                </span>
                <span>GitHub</span>
            </a>
        </div>
    </div>    
</section>

{% endblock body_block %} 

index/templates/index/thanks_message.html
{% extends 'base.html' %}
{% block body_block %}
<section class="hero is-medium is-info " id="main-hero">
    <div class="hero-body">
        <div id="hero-elt">
            <h1 class="title is-1" style="font-weight: 300;">
                Thanks for your sweet words ! 
            </h1>
            <h2 class="subtitle is-3" style="font-weight: 300;">
                I will review your message and come back to you as soon as possible. 
            </h2>
        </div>               
    </div>
</section>
{% endblock body_block %}

index/templates/index/todo.html
{% extends 'base.html' %}
{% block body_block %}
<section class="hero is-small is-info " id="main-hero">
    <div class="hero-body">
        <div id="hero-elt">
            <h1 class="title is-3" style="font-weight: 300;">
                To do List
            </h1>
            <h2 class="subtitle is-5" style="font-weight: 300;">
                Used in this project :  Python / Django / HTML5 / CSS3 / PostgreSQL 
            </h2>
            <a class="subtitle is-5" style="font-weight: 300;" href="https://github.com/Zeble1603/weatherdash">
                <span class="icon">
                    <i class="fab fa-github"></i>
                </span>
                <span>Check the GitHub repository</span>
            </a>
        </div>
    </div>
</section>
<section>
    <content class="container">
        <div class="notification">
            <div class = "columns is-centered">
                <div class = "column is-three-quarters">
                    <h1 class="title has-text-centered">Why?</h1>
                    <p class="has-text-justified">This is the first project I built on my own 
                    after the Django bootcamp. I wanted to put into practice everything I 
                    learned in a simple project, without following any guideline. 
                    </p>
                </div>   
            </div>
            <div class = "columns is-centered">
                <div class = "column is-three-quarters">
                    <h1 class="title has-text-centered">How?</h1>
                    <p class="has-text-justified">
                    I mainly used Class Based views to build this Django project. 
                    I used Foreign keys in my models to link the tasks to the user. 
                    Combined with the proper template tags, it allows the website to display 
                    personal content for each user. 
                    </p>
                </div>   
            </div>
        </div>
    </content>
</section>
{% endblock body_block %}

index/templates/index/weather.html
{% extends 'base.html' %}
{% block body_block %}
<section class="hero is-small is-info " id="main-hero">
    <div class="hero-body">
        <div id="hero-elt">
            <h1><a class="title is-3" style="font-weight: 300;" href = "https://beautiful-weather.herokuapp.com/">
                Beautiful Weather
            </a></h1>
            <h2 class="subtitle is-5" style="font-weight: 300;">
                Used in this project :  Python / Django / HTML5 / CSS3 / PostgreSQL / API calls / JSON
            </h2>
            <a class="subtitle is-5" style="font-weight: 300;" href="https://github.com/Zeble1603/weatherdash">
                <span class="icon">
                    <i class="fab fa-github"></i>
                </span>
                <span>Check the GitHub repository</span>
            </a>
        </div>
    </div>
</section>
<section>
    <content class="container">
        <div class="notification">
            <div class = "columns is-centered">
                <div class = "column is-three-quarters">
                    <h1 class="title has-text-centered">Why?</h1>
                    <p class="has-text-justified">I started this project once I finished
                    the function based view section of the Django bootcamp I was following. 
                    The main goal was to get some experience and knowledge on how to use API : 
                    How does it work ? How can I manipulate them ? I read some articles to get some project ideas. 
                    I chose to work on a website that allows the user to get the weather report of a bunch of cities 
                    he could select, like on the Iphone for example.
                    </p>
                </div>   
            </div>
            <div class = "columns is-centered">
                <div class = "column is-three-quarters">
                    <h1 class="title has-text-centered">How?</h1>
                    <p class="has-text-justified">This website is mainly constructed around a single function based view. 
                    The idea was first to store the url of the api as a variable. A form is here to feed our database of objects, 
                    in that case, they are cities. We then loop over all the objects we have and use their name to fill the api
                    url with the python function format. We get a JSON object that we would store in a dictionary with all the
                    datas we need (temperature, description and an icon representing the current weather). We then store the 
                    dictionary of each city in a list that we will use for the context of the view.  
                    </p>
                </div>   
            </div>
        </div>
    </content>
</section>
{% endblock body_block %}

index/templates/index/work.html
{% extends 'base.html' %}
{% block body_block %}

<section class="hero is-small is-info " id="main-hero">
    <div class="hero-body">
        <div id="hero-elt">
            <h1 class="title is-3" style="font-weight: 300;">
                Work Experience
            </h1>
        </div>
    </div>
</section>

<section>
    <div class="columns is-desktop" style="margin:20px">
        <div class="column">
            <div class="box" style="padding-bottom:48px">
                <div class ="content">
                    <a class="title is-6" href="https://www.edreamsodigeo.com/">eDreams ODIGEO, Barcelona</a>
                    <h3 class="title is-6">Sales Lodging Specialist<br>June 2018 –</h3>
                    <ul>
                        <li>Source, contact and convince the hotels to use our
                        platform ODIGEO Connect in order to facilitate their
                        distribution and increase their online visibility</li>
                        <li>Offer a high-quality service, customer oriented:
                        Assist the hotels by explaining how to use our
                        extranet, facilitate the connectivity with their channel
                        manager</li>
                        <li>Achieve the monthly targets set by our managers</li>
                    </ul> 
                </div>        
            </div>
        </div>
        <div class="column">
            <div class="box">
                <div class ="content">
                    <a class="title is-6" href="https://www.voyageursdumonde.fr/voyage-sur-mesure">Voyageurs du Monde, Paris</a>
                    <h3 class="title is-6">Product Manager Portugal, Tailor Made Travel Designer<br>2014-2018</h3>
                    <ul>
                        <li>Build and sell high-end tailor-made travels. Top seller
                        in the Southern Europe Dpt with a sales revenue of
                        813 000 € in 2017 and a success rate of 42,97% in a
                        higly competitive environment.</li>
                        <li>“Luxury Attitude” referent worker : Provide the best
                        service and the best experiences to our customers.</li>
                        <li>Train 4 new travel agents on selling technics and
                        constructing itineraries.</li>
                        <li>Source and contract new hotels and providers,
                        maintaining an excellent relationship with them by
                        frequently visiting them in Portugal and Spain.</li>
                    </ul> 
                </div>
            </div>
        </div>
    </div>      
</section>                

{% endblock body_block %} 