cv/urls.py
from django import urls
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('',include('index.urls', namespace='index')),
    path("reco/", include('recommendation.urls', namespace='reco')),
    path('admin/', admin.site.urls),
    path("login/", include('account.urls', namespace='account')),
    path("logout/", auth_views.LogoutView.as_view(), name = "logout", kwargs={'next_page': '/'}),
]

index/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('work/', views.WorkView.as_view(), name='work'),
    path('education/', views.EducationView.as_view(), name='education'),
    path('portfolio/', views.ProtfolioView.as_view(), name='portfolio'),
    path('ortho/', views.OrthoView.as_view(), name='ortho'),
    path('weather/', views.WeatherView.as_view(), name='weather'),
    path('todo/', views.TodoView.as_view(), name='todo'),
    path('sudoku/', views.SudokuView.as_view(), name='sudoku'),
    path('contact/', views.MessageCreateView.as_view(), name='contact'),
    path('thanks/', views.ThanksMessageView.as_view(), name='thanks_message'),
    path('dl/<str:filepath>/', views.download_cv),
    path('my_messages',views.MessagesListView.as_view(),name="my_messages"),
    path('my_messages/<pk>/read',views.message_read,name="message_read"),
    path('my_messages/<pk>/delete',views.MessageDelete.as_view(),name="message_delete"),

]

recommendation/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "reco"

urlpatterns = [
    path("", views.ValidRecoListView.as_view(), name = "validreco_list"),
    path("list", views.RecoListView.as_view(), name = "reco_list"),
    path("new", views.RecoCreateView.as_view(), name = "reco_create"),
    path("thanks", views.ThanksTemplateView.as_view(), name = "thanks"),
    path("<pk>", views.RecoDetailView.as_view(), name = "reco_detail"),
    path("<pk>/update", views.RecoUpdateView.as_view(), name = "reco_update"),
    path("<pk>/delete", views.RecoDeleteView.as_view(), name = "reco_delete"),
    path("<pk>/publish", views.reco_publish, name = "reco_publish"),

]

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="{% static 'reco\css\bulma-carousel.min.css' %}">
    <script src="{% static 'reco\js\bulma-carousel.min.js' %}"></script>
    <script src="{% static 'reco\js\script.js' %}"></script>
    <link rel="stylesheet" href="{% static 'index\main.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://kit.fontawesome.com/5d441a8cc7.js" crossorigin="anonymous"></script>
    <title>Blaise De Carvalho</title>
</head>
<body>
    <nav class="navbar is-info has-shadow" role="navigation" aria-label="main navigation" id="main_navbar">
        <div class = "container">    
            <div class="navbar-brand">      
                <a id = "burger" role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
            {% if user.is_authenticated %}
                <div id="my-navbar" class="navbar-menu">
                    <div class="navbar-start">
                        <a class="navbar-item" href="{% url 'index:home' %}">
                            Home
                        </a>
                        <a class="navbar-item" href="{% url 'index:my_messages' %}">
                            My messages
                        </a>
                        <a class="navbar-item" href="{% url 'reco:reco_list' %}">
                            My recommendations
                        </a>
                    </div>
                    <div class="navbar-end">
                        <a style="margin:auto;" class = "button is-info" href="{% url 'logout' %}">Log out</a>
                    </div>
                </div>
            {% else %}
                <div id="my-navbar" class="navbar-menu">
                    <div class="navbar-start">
                        <a class="navbar-item" href="{% url 'index:home' %}">
                            Home
                        </a>
                
                        <a class="navbar-item" href="{% url 'index:work' %}">
                            Work experience
                        </a>

                        <a class="navbar-item" href="{% url 'index:education' %}">
                            Education
                        </a>

                        <a class="navbar-item" href="{% url 'reco:validreco_list' %}">
                            Recommendations
                        </a>
                
                        <div class="navbar-item has-dropdown is-hoverable">
                            <a class="navbar-link" href="{% url 'index:portfolio' %}">
                                Portfolio
                            </a>
                
                        <div class="navbar-dropdown">
                            <a class="navbar-item" href="{% url 'index:portfolio' %}">
                                All projects
                            </a>
                            <a class="navbar-item" href="{% url 'index:ortho' %}">
                                OrthoList 
                            </a>
                            <a class="navbar-item" href="{% url 'index:weather' %}">
                                Beautiful Weather
                            </a>
                            <a class="navbar-item" href="{% url 'index:todo' %}">
                                To do List  
                            </a> 
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </nav>
    {% block body_block %}

    {% endblock body_block %}    
    <section>
        <footer class="footer">
            <div class="content has-text-centered">
                <div class="columns">
                    <div class="column">
                        <a class="footer-link my-links" href="#">Home</a>
                    </div>    
                    <div class="column">
                        <a class="footer-link" href={% url 'index:contact' %}>Contact me</a>                
                    </div>
                    <div class="column">
                        <a class="footer-link" href="https://www.linkedin.com/in/blaisedecarvalho/">Linkedin</a>
                    </div>    
                    <div class="column">
                        <a class="footer-link" href="https://github.com/Zeble1603">Github</a>                
                    </div>
                </div>
            </div>
        </footer>     
    </section>    

<script src= {% static 'index\index.js' %}></script>    
</body>
</html>